### ISSUE TITLE
SplitDataset 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ThiagoSousa** [ArthurFortes/CaseRecommender#2]
For some reason, after I tried to generate 10-folds with the SplitDataset class, I got the following error: 
`File "userknn.py", line 8, in <module>
    SplitDataset(dataset=[traindataset], dir_folds=dir_path, n_folds=2, space_type='\t').execute()
  File "/path/caserec/utils/split_dataset.py", line 95, in execute
    print("total process time:: ", timed(self.divide_dataset()), "sec")
  File "/path/caserec/utils/extra_functions.py", line 34, in timed
    f()
TypeError: 'NoneType' object is not callable`

Although the folds (with train and test) seem to be generated correctly, this error pops up in the end for some reason. My track leads to the split_dataset method in the WriteFile class. I'm not sure if I did something incorrectly, due to the lack of docs for those methods.

**Comment by arthurfortes** [comment]
Hi Thiago! Thank you for reporting the problem.

The problem is in the method execute:

Wrong:

`print("total process time:: ", timed(self.divide_dataset()), "sec")`

Right:

`print("total process time:: ", timed(self.divide_dataset), "sec")`

I release a new version. Let me know if this solved your problem.

Regards.
